import CryptoKit
import Foundation

/// Codex: everything Tako adds is passed as `-c` overrides by the wrapper; the thread id is
/// learned from its hooks.
struct CodexAdapter: AgentAdapter {
    let command = "codex"

    // MARK: - Launch

    func install(hookPort: UInt16?) {
        AgentIntegration.writeExecutable(Self.wrapperScript(ht: AgentIntegration.htPath),
                                         to: AgentIntegration.binDirectory.appendingPathComponent(command))
    }

    /// Hooks report state; `notify` (turn complete) and OSC 9 notifications stay as the fallback
    /// for a Codex with hooks turned off.
    ///
    /// Codex runs behind its own app-server, private to this session: the server runs the agent
    /// (so it gets Tako's hooks, notify, MCP servers and the launch's `-c` settings, which the TUI
    /// doesn't pass on), and the TUI attaches to it here with `--remote`, so Codex still shows in
    /// this terminal. Tako follows the server as a second client and gets approvals as JSON-RPC
    /// requests (`CodexAppServer`). It listens on a loopback port Codex picks, behind a random
    /// capability token, and dies with the TUI. Both stay in this terminal's process tree and
    /// environment. If the server isn't up within 5 s, Codex runs on its own (`--no-daemon`) as
    /// before.
    static func wrapperScript(ht: String) -> String {
        let overrides = hookOverrides(ht: ht)
        let hooks = stride(from: 0, to: overrides.count, by: 2)
            .map { "  \(overrides[$0]) \(shellQuote(overrides[$0 + 1])) \\" }.joined(separator: "\n")
        // For whichever process runs the agent: its app-server, or Codex itself.
        let tako = hooks + "\n" + #"""
          -c "notify=[\"$HT_DIR/bin/ht\",\"hook\",\"codex-notify\"]" \
          -c "mcp_servers.hyperterm.command=\"$HT_DIR/bin/ht\"" \
          -c 'mcp_servers.hyperterm.args=["mcp"]' \
          -c "mcp_servers.browser.command=\"$HT_DIR/bin/ht\"" \
          -c 'mcp_servers.browser.args=["browser-mcp","\#(AgentBrowser.preferredPort)"]' \
        """#
        let tui = #"""
          -c 'tui.notification_method="osc9"' \
          -c 'tui.notification_condition="always"' \
        """#
        return #"""
        #!/bin/sh
        # Generated by Tako. Runs the real Codex with Tako hooks, notify + MCP attached.
        HT_DIR="${HT_HOME:-$HOME/.hyperterm}"
        PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -vx "$HT_DIR/bin" | paste -sd: -)
        export PATH
        # The user's own stdio MCP servers start on first use (ht mcp-lazy).
        LAZY=$("$HT_DIR/bin/ht" mcp-lazy-config codex 2>/dev/null)
        # Codex's own app-server for this session; Tako follows it for approvals.
        SESSION_C=
        PREV=
        for ARG in "$@"; do
          [ "$PREV" = "-c" ] && SESSION_C="$SESSION_C -c '$(printf '%s' "$ARG" | sed "s/'/'\\\\''/g")'"
          PREV=$ARG
        done
        # Those of servers that are gone (their terminal was closed) are swept first.
        for OLD in "${TMPDIR:-/tmp}"/tako-codex.*; do
          [ -f "$OLD/pid" ] && ! kill -0 "$(cat "$OLD/pid")" 2>/dev/null && rm -rf "$OLD"
        done
        RUN=$(mktemp -d "${TMPDIR:-/tmp}/tako-codex.XXXXXX" 2>/dev/null)
        if [ -n "$HT_SESSION_ID" ] && [ -n "$RUN" ] && head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$RUN/token"; then
          (eval "set -- $LAZY $SESSION_C"; exec codex app-server --listen ws://127.0.0.1:0 \
            --ws-auth capability-token --ws-token-file "$RUN/token" \
        \#(tako)
            "$@") > "$RUN/log" 2>&1 &
          SERVER=$!
          echo $SERVER > "$RUN/pid"
          URL=
          TRIES=0
          while [ -z "$URL" ] && [ $TRIES -lt 50 ] && kill -0 $SERVER 2>/dev/null; do
            sleep 0.1
            TRIES=$((TRIES + 1))
            URL=$(sed -n 's|^ *listening on: \(ws://127\.0\.0\.1:[0-9]*\)$|\1|p' "$RUN/log")
          done
          if [ -n "$URL" ]; then
            trap 'kill $SERVER 2>/dev/null; rm -rf "$RUN"' EXIT
            trap 'exit 129' HUP
            trap 'exit 143' TERM
            "$HT_DIR/bin/ht" hook codex-app-server "{\"url\":\"$URL\",\"token_file\":\"$RUN/token\"}"
            TAKO_CODEX_TOKEN=$(cat "$RUN/token") codex --remote "$URL" --remote-auth-token-env TAKO_CODEX_TOKEN \
        \#(tui)
              "$@"
            exit
          fi
          kill $SERVER 2>/dev/null
        fi
        [ -n "$RUN" ] && rm -rf "$RUN"
        eval "set -- $LAZY \"\$@\""
        exec codex --no-daemon \
        \#(tako)
        \#(tui)
          "$@"
        """#
    }

    /// Tako's hooks: event, Codex's key for it, `ht` arguments, timeout in seconds (an
    /// Interrupt hook gets at most 3).
    private static let hooks: [(event: String, key: String, arguments: String, timeout: Int)] = [
        ("SessionStart", "session_start", "hook codex", 10),
        ("UserPromptSubmit", "user_prompt_submit", "hook codex", 10),
        ("PreToolUse", "pre_tool_use", "hook codex", 10),
        ("PostToolUse", "post_tool_use", "hook codex", 10),
        // Held open until the user decides in Tako (or answers in the terminal).
        ("PermissionRequest", "permission_request", "permission codex", 600),
        ("Stop", "stop", "hook codex", 10),
        ("Interrupt", "interrupt", "hook codex", 3),
    ]

    /// Codex runs a hook that isn't admin-managed only once its exact definition is trusted (by
    /// hash, under `hooks.state`), and it reads that trust from `-c` flags as well as from
    /// config.toml. So each hook comes with its own trust: nothing to review in /hooks, no
    /// --dangerously-bypass-hook-trust (which would also run the user's untrusted hooks), and
    /// nothing written to the user's config. Verified on codex-cli 0.160.1 (`codex exec`): with
    /// this trust SessionStart, UserPromptSubmit, Pre/PostToolUse and Stop all ran; without it,
    /// or with a wrong hash, none ran and Codex said nothing.
    static func hookOverrides(ht: String) -> [String] {
        var overrides: [String] = []
        var trust: [String] = []
        for hook in hooks {
            let command = "\(ht) \(hook.arguments)"
            overrides += ["-c", "hooks.\(hook.event)=[{hooks=[{type=\"command\",command=\(LazyMCP.tomlString(command)),timeout=\(hook.timeout)}]}]"]
            let key = "/<session-flags>/config.toml:\(hook.key):0:0"
            let hash = hookHash(event: hook.key, command: command, timeout: hook.timeout)
            trust.append("\(LazyMCP.tomlString(key))={trusted_hash=\(LazyMCP.tomlString(hash))}")
        }
        return overrides + ["-c", "hooks.state={\(trust.joined(separator: ","))}"]
    }

    /// Codex's trust hash for one command hook: SHA-256 of its normalized definition as compact
    /// JSON with sorted keys.
    static func hookHash(event: String, command: String, timeout: Int) -> String {
        let identity: [String: Any] = ["event_name": event,
                                       "hooks": [["async": false, "command": command, "timeout": timeout, "type": "command"]]]
        let data = (try? JSONSerialization.data(withJSONObject: identity, options: [.sortedKeys, .withoutEscapingSlashes])) ?? Data()
        return "sha256:" + SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    func launchCommand(for spec: LaunchSpec, resume: Bool, options: String, extra: String, prompt: String) -> String {
        if resume, let thread = spec.agentSessionId, isSafeIdentifier(thread) {
            return "\(wrapper) resume \(shellQuote(thread))\(options)\(extra)\n"
        }
        return "\(wrapper)\(options)\(extra)\(prompt)\n"
    }

    /// Codex 0.160 takes only `on-request` and `never` approvals, so "ask first" is a read-only
    /// sandbox where every edit or command beyond reading asks; Plan is the same, by intent.
    func arguments(for options: AgentOptions) -> [String] {
        var args: [String] = []
        if let model = options.model.flatMap(AgentOptions.validModel) { args += ["-m", model] }
        if let effort = options.effort { args += ["-c", "model_reasoning_effort=\"\(effort.rawValue)\""] }
        switch options.mode {
        case .supervised?, .plan?: args += ["--ask-for-approval", "on-request", "--sandbox", "read-only"]
        case .acceptEdits?: args += ["--ask-for-approval", "on-request", "--sandbox", "workspace-write"]
        case .fullAccess?: args += ["--dangerously-bypass-approvals-and-sandbox"]
        case nil: break
        }
        return args
    }

    let assignsSessionID = false

    func resumeCommand(_ id: String) -> String { "codex resume \(id)" }

    // MARK: - Conversation

    let exitCommand = "/quit"
    let newConversationCommand = "/new"

    func canSleep(_ spec: LaunchSpec) -> Bool { true }

    /// The thread's rollout log under `sessions/YYYY/MM/DD/`.
    func transcriptFile(id: String, cwds: [String], root: URL) -> URL? {
        CodexUsage.logFile(thread: id, in: root)
    }

    func renderTranscript(_ text: Substring) -> [String] { AgentTranscript.renderCodex(text) }

    func usage(id: String, root: URL) -> CodexUsage.Reading? {
        CodexUsage.logFile(thread: id, in: root)
            .flatMap { CodexUsage.tail(of: $0) }
            .flatMap { CodexUsage.latest(in: $0) }
    }

    /// With hooks turned off Codex reports nothing until its first turn ends; its running
    /// process stands in, and turns start when work starts from rest.
    let reportsStart = false
    let reportsPrompts = false

    // MARK: - Accounts

    let homeFolder = ".codex"
    let homeVariable = "CODEX_HOME"
    let historyFolder = "sessions"
    let signInCommand = "codex login"

    func seed(_ directory: URL, from home: URL) {
        // Copied rather than linked: Codex rewrites config.toml (trust, notices).
        let config = home.appendingPathComponent("config.toml")
        var text = (try? String(contentsOf: config, encoding: .utf8)) ?? ""
        if !text.contains("cli_auth_credentials_store") { text = "cli_auth_credentials_store = \"file\"\n" + text }
        try? text.write(to: directory.appendingPathComponent("config.toml"), atomically: true, encoding: .utf8)
        for shared in ["AGENTS.md", "prompts", "skills", "rules"] { AccountStore.link(shared, from: home, into: directory) }
    }

    func signedInEmail(home: URL, isDefault: Bool) -> String? {
        guard let data = try? Data(contentsOf: home.appendingPathComponent("auth.json")),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return nil }
        if let token = (json["tokens"] as? [String: Any])?["id_token"] as? String, let email = AccountStore.jwtEmail(token) { return email }
        return json["OPENAI_API_KEY"] is String ? "API key" : nil
    }

    // MARK: - Screen and processes

    /// Old and new wording; "trust and continue" is 0.160's first option, which never wraps.
    let trustMarkers = ["allow codex to work in this folder", "codex can read, edit, and run files here", "trust and continue"]
    /// 0.160's first-run screen when signed out.
    let signInMarkers = ["sign in with chatgpt to use codex", "sign in with device code"]
    let promptMarker = "›"
    let optionsAloneMakeDialog = true

    /// The native binary, or npm's `node …/bin/codex(.js)` launcher in front of it.
    func isCLIProcess(name: String, path: String?, script: String?) -> Bool {
        name == command || Self.isScript(script, package: "@openai/codex", command: command)
    }
}
