import AppKit
import Foundation

/// Codex: everything Kuronami adds is passed as `-c` overrides by the wrapper; the thread id is
/// learned from what Codex reports.
struct CodexAdapter: AgentAdapter {
    let command = "codex"

    // MARK: - Launch

    func install(hookPort: UInt16?) {
        AgentIntegration.writeExecutable(Self.wrapperScript(), to: AgentIntegration.binDirectory.appendingPathComponent(command))
    }

    /// Codex hooks need per-hash trust review, so status comes from `notify` (turn complete) and
    /// TUI OSC 9 notifications (approvals), both of which work without trust prompts.
    private static func wrapperScript() -> String {
        """
        #!/bin/sh
        # Generated by Kuronami. Runs the real Codex with Kuronami notify + MCP attached.
        HT_DIR="${HT_HOME:-$HOME/.hyperterm}"
        PATH=$(printf '%s' "$PATH" | tr ':' '\\n' | grep -vx "$HT_DIR/bin" | paste -sd: -)
        export PATH
        # The user's own stdio MCP servers start on first use (ht mcp-lazy).
        LAZY=$("$HT_DIR/bin/ht" mcp-lazy-config codex 2>/dev/null)
        eval "set -- $LAZY \\"\\$@\\""
        exec codex \\
          -c "notify=[\\"$HT_DIR/bin/ht\\",\\"hook\\",\\"codex-notify\\"]" \\
          -c 'tui.notification_method="osc9"' \\
          -c 'tui.notification_condition="always"' \\
          -c "mcp_servers.hyperterm.command=\\"$HT_DIR/bin/ht\\"" \\
          -c 'mcp_servers.hyperterm.args=["mcp"]' \\
          -c "mcp_servers.browser.command=\\"$HT_DIR/bin/ht\\"" \\
          -c 'mcp_servers.browser.args=["browser-mcp","\(AgentBrowser.preferredPort)"]' \\
          "$@"
        """
    }

    /// Codex reads hooks from ~/.codex/hooks.json; this adds Kuronami's PermissionRequest hook
    /// there (keeping any others) after the user agrees. Codex asks the user to trust it once (/hooks).
    @MainActor
    static func installApprovalHook() {
        let alert = NSAlert()
        alert.messageText = "Answer Codex approvals from Kuronami?"
        alert.informativeText = "Adds a PermissionRequest hook to ~/.codex/hooks.json that asks Kuronami (only for Codex sessions started in Kuronami; elsewhere it does nothing). Codex will ask you to review and trust the hook once via /hooks."
        alert.addButton(withTitle: "Add Hook")
        alert.addButton(withTitle: "Cancel")
        guard alert.runModal() == .alertFirstButtonReturn else { return }
        let url = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".codex/hooks.json")
        var root = (try? Data(contentsOf: url)).flatMap { try? JSONSerialization.jsonObject(with: $0) as? [String: Any] } ?? [:]
        var hooks = root["hooks"] as? [String: Any] ?? [:]
        var groups = hooks["PermissionRequest"] as? [[String: Any]] ?? []
        let command = "\(AgentIntegration.htPath) permission codex"
        let exists = groups.contains { (($0["hooks"] as? [[String: Any]]) ?? []).contains { $0["command"] as? String == command } }
        if !exists {
            groups.append(["hooks": [["type": "command", "command": command, "timeout": 600, "statusMessage": "Waiting for approval in Kuronami"]]])
        }
        hooks["PermissionRequest"] = groups
        root["hooks"] = hooks
        try? FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        if let data = try? JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys]) {
            try? data.write(to: url, options: .atomic)
        }
    }

    func launchCommand(for spec: LaunchSpec, resume: Bool, options: String, extra: String, prompt: String) -> String {
        if resume, let thread = spec.agentSessionId, isSafeIdentifier(thread) {
            return "\(wrapper) resume \(shellQuote(thread))\(options)\(extra)\n"
        }
        return "\(wrapper)\(options)\(extra)\(prompt)\n"
    }

    func arguments(for options: AgentOptions) -> [String] {
        var args: [String] = []
        if let model = options.model.flatMap(AgentOptions.validModel) { args += ["-m", model] }
        if let effort = options.effort { args += ["-c", "model_reasoning_effort=\"\(effort.rawValue)\""] }
        switch options.mode {
        case .supervised?: args += ["--ask-for-approval", "untrusted", "--sandbox", "workspace-write"]
        case .acceptEdits?: args += ["--full-auto"]
        case .plan?: args += ["--ask-for-approval", "on-request", "--sandbox", "read-only"]
        case .fullAccess?: args += ["--dangerously-bypass-approvals-and-sandbox"]
        case nil: break
        }
        return args
    }

    let assignsSessionID = false

    func resumeCommand(_ id: String) -> String { "codex resume \(id)" }

    // MARK: - Conversation

    let exitCommand = "/quit"
    let newConversationCommand = "/new"

    func canSleep(_ spec: LaunchSpec) -> Bool { true }

    /// The thread's rollout log under `sessions/YYYY/MM/DD/`.
    func transcriptFile(id: String, cwds: [String], root: URL) -> URL? {
        CodexUsage.logFile(thread: id, in: root)
    }

    func renderTranscript(_ text: Substring) -> [String] { AgentTranscript.renderCodex(text) }

    func usage(id: String, root: URL) -> CodexUsage.Reading? {
        CodexUsage.logFile(thread: id, in: root)
            .flatMap { CodexUsage.tail(of: $0) }
            .flatMap { CodexUsage.latest(in: $0) }
    }

    /// Codex reports nothing until its first turn ends.
    let reportsStart = false
    let reportsPrompts = false

    // MARK: - Accounts

    let homeFolder = ".codex"
    let homeVariable = "CODEX_HOME"
    let historyFolder = "sessions"
    let signInCommand = "codex login"

    func seed(_ directory: URL, from home: URL) {
        // Copied rather than linked: Codex rewrites config.toml (trust, notices).
        let config = home.appendingPathComponent("config.toml")
        var text = (try? String(contentsOf: config, encoding: .utf8)) ?? ""
        if !text.contains("cli_auth_credentials_store") { text = "cli_auth_credentials_store = \"file\"\n" + text }
        try? text.write(to: directory.appendingPathComponent("config.toml"), atomically: true, encoding: .utf8)
        for shared in ["AGENTS.md", "prompts", "skills", "rules"] { AccountStore.link(shared, from: home, into: directory) }
    }

    func signedInEmail(home: URL, isDefault: Bool) -> String? {
        guard let data = try? Data(contentsOf: home.appendingPathComponent("auth.json")),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return nil }
        if let token = (json["tokens"] as? [String: Any])?["id_token"] as? String, let email = AccountStore.jwtEmail(token) { return email }
        return json["OPENAI_API_KEY"] is String ? "API key" : nil
    }

    // MARK: - Screen and processes

    /// Old and new wording.
    let trustMarkers = ["allow codex to work in this folder", "codex can read, edit, and run files here"]
    let promptMarker = "›"
    let optionsAloneMakeDialog = true

    func isCLIProcess(name: String, path: String?) -> Bool { name == command }
}
