#!/bin/sh
# Regenerates Sources/ht/BrowserMCPTools.swift: chrome-devtools-mcp's initialize and tools/list
# replies, which `ht browser-mcp` serves without starting the server. Run after bumping the
# chrome-devtools-mcp version in BrowserMCP.swift.
set -e
cd "$(dirname "$0")/.."
package=$(sed -n 's/^let chromeDevtoolsMCP = "\(.*\)"$/\1/p' Sources/ht/BrowserMCP.swift)
[ -n "$package" ] || { echo "no chromeDevtoolsMCP in BrowserMCP.swift" >&2; exit 1; }
scratch=$(mktemp -d)
trap 'rm -rf "$scratch"' EXIT
out=Sources/ht/BrowserMCPTools.swift

CHROME_DEVTOOLS_MCP_NO_UPDATE_CHECKS=1 PACKAGE="$package" OUT="$out" node -e '
const { spawn } = require("child_process");
const fs = require("fs");
const child = spawn("npx", ["-y", process.env.PACKAGE, "--browser-url", "http://127.0.0.1:9",
  "--no-usage-statistics", "--no-performance-crux"], { stdio: ["pipe", "pipe", "inherit"] });
const send = (m) => child.stdin.write(JSON.stringify(m) + "\n");
const replies = {};
let buffer = "";
child.stdout.on("data", (chunk) => {
  buffer += chunk;
  let newline;
  while ((newline = buffer.indexOf("\n")) >= 0) {
    const message = JSON.parse(buffer.slice(0, newline));
    buffer = buffer.slice(newline + 1);
    if (message.id === undefined) continue;
    replies[message.id] = message.result;
    if (message.id === 1) {
      send({ jsonrpc: "2.0", method: "notifications/initialized" });
      send({ jsonrpc: "2.0", id: 2, method: "tools/list" });
    } else {
      const json = JSON.stringify({ initialize: replies[1], tools: replies[2].tools }, null, 2);
      fs.writeFileSync(process.env.OUT,
        "// Generated by scripts/browser-mcp-tools.sh from " + process.env.PACKAGE + ". Do not edit;\n" +
        "// rerun the script whenever BrowserMCP.swift moves to another chrome-devtools-mcp version.\n\n" +
        "/// chrome-devtools-mcp'\''s initialize result and tools, served before the server is started.\n" +
        "let browserMCPCapture = #\"\"\"\n" + json + "\n\"\"\"#\n");
      child.kill();
      process.exit(0);
    }
  }
});
send({ jsonrpc: "2.0", id: 1, method: "initialize",
  params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "ht", version: "1" } } });
setTimeout(() => { console.error("chrome-devtools-mcp did not answer"); child.kill(); process.exit(1); }, 120000);
' "$scratch"
echo "wrote $out"
