import AppKit
import Foundation

/// Generates the files that wire Claude Code and Codex into Kuronami without touching the user's
/// own config: hooks and MCP are passed per launch (`claude --settings/--mcp-config`,
/// `codex -c ...`) through small wrapper scripts in ~/.hyperterm/bin.
enum AgentIntegration {
    static var root: URL { ControlPaths.supportDirectory }
    static var binDirectory: URL { root.appendingPathComponent("bin") }
    static var htPath: String { binDirectory.appendingPathComponent("ht").path }

    /// Idempotent; run at every launch because the app bundle (and its `ht`) can move.
    static func install() {
        let fm = FileManager.default
        try? fm.createDirectory(at: binDirectory, withIntermediateDirectories: true)
        linkBundledCLI()
        write(claudeSettings(), to: root.appendingPathComponent("claude-settings.json"))
        write(mcpConfig(), to: root.appendingPathComponent("mcp.json"))
        writeExecutable(claudeWrapper(), to: binDirectory.appendingPathComponent("claude"))
        writeExecutable(codexWrapper(), to: binDirectory.appendingPathComponent("codex"))
    }

    private static func linkBundledCLI() {
        guard let bundled = Bundle.main.resourceURL?.appendingPathComponent("bin/ht").path,
              FileManager.default.fileExists(atPath: bundled) else { return }
        try? FileManager.default.removeItem(atPath: htPath)
        try? FileManager.default.createSymbolicLink(atPath: htPath, withDestinationPath: bundled)
    }

    // MARK: - Claude

    private static func claudeSettings() -> String {
        let events = ["SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "PostToolUseFailure", "Notification",
                      "Stop", "StopFailure", "SessionEnd", "TaskCreated", "TaskCompleted", "SubagentStart"]
        let hook: [String: Any] = ["type": "command", "command": "\(htPath) hook claude", "timeout": 5]
        var hooks: [String: Any] = Dictionary(uniqueKeysWithValues: events.map { ($0, [["hooks": [hook]]]) })
        // Held open until the user decides in Kuronami (or answers in the terminal).
        let permission: [String: Any] = ["type": "command", "command": "\(htPath) permission claude", "timeout": 600]
        hooks["PermissionRequest"] = [["matcher": "*", "hooks": [permission]]]
        // Read-only and self-describing tools are safe to run without a prompt; messaging other
        // agents and starting servers still ask.
        let allow = ["list_terminals", "read_terminal", "rename_terminal", "set_status"].map { "mcp__hyperterm__" + $0 }
            + browserReadOnlyTools.map { "mcp__browser__" + $0 }
        // statusLine feeds cost/context/rate limits to Kuronami, then prints the user's own
        // statusline unchanged (`ht statusline` runs it).
        let statusLine: [String: Any] = ["type": "command", "command": "\(htPath) statusline", "padding": 0]
        return json(["hooks": hooks, "permissions": ["allow": allow], "statusLine": statusLine])
    }

    private static func mcpConfig() -> String {
        json(["mcpServers": [
            "hyperterm": ["command": htPath, "args": ["mcp"]],
            "browser": ["command": htPath, "args": ["browser-mcp", String(AgentBrowser.preferredPort)]],
        ]])
    }

    /// Browser tools that only look: screenshots, page snapshots, console and network logs.
    /// Navigating, clicking, typing, and running scripts still ask.
    private static let browserReadOnlyTools = [
        "list_pages", "take_snapshot", "take_screenshot", "list_console_messages", "get_console_message",
        "list_network_requests", "get_network_request", "get_css_styles", "wait_for",
    ]

    /// Strips our bin dir from PATH so `claude` resolves to the real binary, then adds Kuronami's
    /// hooks and MCP server. User hooks still run: `--settings` merges with user settings.
    private static func claudeWrapper() -> String {
        """
        #!/bin/sh
        # Generated by Kuronami. Runs the real Claude Code with Kuronami hooks + MCP attached.
        HT_DIR="${HT_HOME:-$HOME/.hyperterm}"
        PATH=$(printf '%s' "$PATH" | tr ':' '\\n' | grep -vx "$HT_DIR/bin" | paste -sd: -)
        export PATH
        CHANNEL=""
        [ "$HT_CHANNELS" = "1" ] && CHANNEL="--dangerously-load-development-channels server:hyperterm"
        # --no-chrome: agents here browse in Kuronami's own browser (the "browser" MCP server),
        # not the user's everyday Chrome through Claude in Chrome.
        exec claude --settings "$HT_DIR/claude-settings.json" --mcp-config "$HT_DIR/mcp.json" \(AgentBrowser.agentsMayUseOutsideChrome ? "" : "--no-chrome ")$CHANNEL "$@"
        """
    }

    // MARK: - Codex

    /// Codex hooks need per-hash trust review, so status comes from `notify` (turn complete) and
    /// TUI OSC 9 notifications (approvals), both of which work without trust prompts.
    private static func codexWrapper() -> String {
        """
        #!/bin/sh
        # Generated by Kuronami. Runs the real Codex with Kuronami notify + MCP attached.
        HT_DIR="${HT_HOME:-$HOME/.hyperterm}"
        PATH=$(printf '%s' "$PATH" | tr ':' '\\n' | grep -vx "$HT_DIR/bin" | paste -sd: -)
        export PATH
        exec codex \\
          -c "notify=[\\"$HT_DIR/bin/ht\\",\\"hook\\",\\"codex-notify\\"]" \\
          -c 'tui.notification_method="osc9"' \\
          -c 'tui.notification_condition="always"' \\
          -c "mcp_servers.hyperterm.command=\\"$HT_DIR/bin/ht\\"" \\
          -c 'mcp_servers.hyperterm.args=["mcp"]' \\
          -c "mcp_servers.browser.command=\\"$HT_DIR/bin/ht\\"" \\
          -c 'mcp_servers.browser.args=["browser-mcp","\(AgentBrowser.preferredPort)"]' \\
          "$@"
        """
    }

    /// Codex reads hooks from ~/.codex/hooks.json; this adds Kuronami's PermissionRequest hook
    /// there (keeping any others) after the user agrees. Codex asks the user to trust it once (/hooks).
    @MainActor
    static func installCodexApprovalHook() {
        let alert = NSAlert()
        alert.messageText = "Answer Codex approvals from Kuronami?"
        alert.informativeText = "Adds a PermissionRequest hook to ~/.codex/hooks.json that asks Kuronami (only for Codex sessions started in Kuronami; elsewhere it does nothing). Codex will ask you to review and trust the hook once via /hooks."
        alert.addButton(withTitle: "Add Hook")
        alert.addButton(withTitle: "Cancel")
        guard alert.runModal() == .alertFirstButtonReturn else { return }
        let url = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".codex/hooks.json")
        var root = (try? Data(contentsOf: url)).flatMap { try? JSONSerialization.jsonObject(with: $0) as? [String: Any] } ?? [:]
        var hooks = root["hooks"] as? [String: Any] ?? [:]
        var groups = hooks["PermissionRequest"] as? [[String: Any]] ?? []
        let command = "\(htPath) permission codex"
        let exists = groups.contains { (($0["hooks"] as? [[String: Any]]) ?? []).contains { $0["command"] as? String == command } }
        if !exists {
            groups.append(["hooks": [["type": "command", "command": command, "timeout": 600, "statusMessage": "Waiting for approval in Kuronami"]]])
        }
        hooks["PermissionRequest"] = groups
        root["hooks"] = hooks
        try? FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        if let data = try? JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys]) {
            try? data.write(to: url, options: .atomic)
        }
    }

    // MARK: - Launch

    static func surfaceLaunch(for spec: LaunchSpec) -> SurfaceLaunch {
        var environment = [
            "HT_SESSION_ID": spec.id.uuidString,
            "HT_LABEL": spec.label,
            "HT_SOCKET": ControlPaths.socketPath,
        ]
        if spec.kind == .claude && SessionStore.channelsEnabled { environment["HT_CHANNELS"] = "1" }
        if let port = spec.port {
            environment["PORT"] = String(port)
            environment["HT_PORT"] = String(port)
        }
        // The account's config root (CLAUDE_CONFIG_DIR / CODEX_HOME). A sign-in terminal for an
        // account is a shell carrying the same variables.
        if let id = spec.account {
            let kind = spec.kind.isAgent ? spec.kind : (spec.accountKind ?? .claude)
            environment.merge(MainActor.assumeIsolated { AccountStore.shared.account(id, kind: kind)?.environment ?? [:] }) { _, new in new }
        }
        return SurfaceLaunch(workingDirectory: expandTilde(spec.cwd), command: nil, environment: environment)
    }

    /// Agents and servers are typed into a real login shell so the user's PATH and rc files
    /// apply, the command shows in history, and the shell remains after the program exits.
    /// Everything Kuronami interpolates is shell-quoted; only the user's own server command and
    /// agent arguments (typed by the user, never by agents) are passed through as written.
    static func initialInput(for spec: LaunchSpec, resume: Bool, task: String? = nil) -> String? {
        let extra = spec.command.map { " " + $0 } ?? ""
        let prompt = task.flatMap { $0.isEmpty ? nil : " " + shellQuote($0) } ?? ""
        func options(_ cli: AgentCLI) -> String {
            (spec.options?.arguments(for: cli) ?? []).map { " " + shellQuote($0) }.joined()
        }
        switch spec.kind {
        case .claude:
            var args = "--name \(shellQuote(spec.label))"
            if resume, let id = spec.agentSessionId, isSafeIdentifier(id) {
                args += " --resume \(shellQuote(id))"
            } else if let parent = spec.forkOf, isSafeIdentifier(parent) {
                // A fork continues the parent's conversation under a new session id; the parent
                // is untouched. Claude finds conversations by folder, so a fork starts in the
                // parent's own working folder.
                args += " --resume \(shellQuote(parent)) --fork-session"
            } else {
                // Pre-assigned, so resume never waits on a hook to learn the id.
                if let id = spec.agentSessionId, UUID(uuidString: id) != nil { args += " --session-id \(shellQuote(id))" }
                if let worktree = spec.worktreeName { args += " --worktree \(shellQuote(worktree))" }
            }
            return "\(shellQuote(binDirectory.appendingPathComponent("claude").path)) \(args)\(options(.claude))\(extra)\(prompt)\n"
        case .codex:
            if resume, let thread = spec.agentSessionId, isSafeIdentifier(thread) {
                return "\(shellQuote(binDirectory.appendingPathComponent("codex").path)) resume \(shellQuote(thread))\(options(.codex))\(extra)\n"
            }
            return "\(shellQuote(binDirectory.appendingPathComponent("codex").path))\(options(.codex))\(extra)\(prompt)\n"
        case .server, .shell:
            return spec.command.map { $0 + "\n" }
        case .browser:
            return nil
        }
    }

    // MARK: - Helpers

    private static func json(_ object: Any) -> String {
        let data = (try? JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted, .sortedKeys])) ?? Data()
        return String(decoding: data, as: UTF8.self)
    }

    private static func write(_ content: String, to url: URL) {
        try? content.write(to: url, atomically: true, encoding: .utf8)
    }

    private static func writeExecutable(_ content: String, to url: URL) {
        write(content, to: url)
        try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    }
}

func expandTilde(_ path: String) -> String {
    (path as NSString).expandingTildeInPath
}

/// "~/Code/hyperterm" stays; deeper paths keep the last two components: "…/app/web".
func shortPath(_ path: String) -> String {
    let abbreviated = abbreviateHome(path)
    let parts = abbreviated.split(separator: "/")
    guard parts.count > 3 else { return abbreviated }
    return "…/" + parts.suffix(2).joined(separator: "/")
}

/// Single-quotes for POSIX shells: 'it'\''s'.
func shellQuote(_ value: String) -> String {
    "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
}

func abbreviateHome(_ path: String) -> String {
    let home = FileManager.default.homeDirectoryForCurrentUser.path
    return path.hasPrefix(home) ? "~" + path.dropFirst(home.count) : path
}
